config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('links/', include('links.urls')),
]

home/urls.py
from django.urls import path

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<str:token>/', views.RedirectUrlView.as_view(), name='redirect_url'),
]

links/urls.py
from django.urls import path

from links import views

app_name = 'links'

urlpatterns = [
    path('create/', views.CreateLink.as_view(), name='create_link'),
    path('list/', views.LinkListView.as_view(), name='link_list'),
    path('<int:pk>/', views.LinkDetailView.as_view(), name='link_detail'),
    path('delete/<int:pk>', views.DeleteLink.as_view(), name='delete_link'),
]

links/models.py
from django.db import models


class Link(models.Model):
    url = models.URLField()
    tiny_url = models.URLField()
    token = models.CharField(max_length=16)

    def __str__(self):
        return self.url

users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

home/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, RedirectView

from links.models import Link


class HomeView(TemplateView):
    template_name = 'home/home.html'


class RedirectUrlView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        url_obj = get_object_or_404(Link, token=kwargs['token'])
        return url_obj.url

links/views.py
from uuid import uuid4

from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, DeleteView, ListView

from links.models import Link


class CreateLink(CreateView):
    model = Link
    fields = ['url']
    template_name = 'links/create_link.html'

    def form_valid(self, form):
        host_url = self.request.build_absolute_uri('/')
        token = str(uuid4()).split('-')[0]
        url = f'{host_url}{token}'
        form.instance.tiny_url = url
        form.instance.token = token
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('links:link_detail', kwargs={'pk': self.object.pk})


class LinkDetailView(DetailView):
    model = Link
    template_name = 'links/link_detail.html'
    context_object_name = 'link'


class LinkListView(ListView):
    model = Link
    template_name = 'links/link_list.html'
    context_object_name = 'links'


class DeleteLink(DeleteView):
    model = Link
    template_name = 'links/delete_link.html'
    success_url = reverse_lazy('links:link_list')

home/templates/home/home.html
{% extends "base.html"%}

{% block title %}Home Page{% endblock %}

{% block content %}
    <h1>Welcome to TinyUrl website!</h1>
{% endblock %}

links/templates/links/create_link.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add Link{% endblock %}

{% block content %}
    <h2>Add new link</h2>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success">Add</button>
    </form>
{% endblock %}

links/templates/links/delete_link.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Delete Link{% endblock %}

{% block content %}
    <h2>Are you sure?</h2>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
{% endblock %}

links/templates/links/link_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Link{% endblock %}

{% block content %}
    <h2>Add new link</h2>

    <form action="" method="GET">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="button" class="btn btn-primary">Add another</button>
    </form>
{% endblock %}

links/templates/links/link_list.html
{% extends "base.html" %}

{% block title %}Link List{% endblock %}

{% block content %}
    <h2>Your links</h2>

    <ul class="list-group list-group-flush">
        {% for link in links %}
            <a href="#" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">List group item heading</h5>
                <small class="text-muted">3 days ago</small>
                </div>
                <p class="mb-1">Some placeholder content in a paragraph.</p>
                <p class="mb-1">Some placeholder content in a paragraph.</p>
                <small class="text-muted">And some muted small print.</small>
            </a>
        {% empty %}
            <p>You have no added links yet.</p>
        {% endfor %}
    </ul>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'images/logo.ico' %}" alt="Home" width="50"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account_signup' %}">Create free acount</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">Login</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'links:create_link' %}">Add link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'links:link_list' %}">Your links</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>